name: "Generate infrastructure"
description: "Generate infrastructure"
inputs:
  snowflakeAccount:
    description: "Snowflake account name"
    required: true
  snowflakeUser:
    description: "Snowflake user name"
    required: true
  snowflakePrivateKey:
    description: "Snowflake private key file"
    required: true
  snowflakeOrganization:
    description: "Snowflake organization name"
    required: true
  testingDataset:
    default: "false"
    description: "Generate testing dataset"
    required: false
  demoDataset:
    default: "true"
    description: "Generate demo dataset"
    required: false

runs:
  using: composite
  steps:
    - name: Generate infrastructure
      shell: bash
      run: make gen-test-infra
      env:
        TF_VAR_snowflake_account: ${{ inputs.snowflakeAccount }}
        TF_VAR_snowflake_organization: ${{ inputs.snowflakeOrganization }}
        TF_VAR_snowflake_user: ${{ inputs.snowflakeUser }}
        TF_VAR_snowflake_private_key_file: ${{ inputs.snowflakePrivateKey }}
        TF_VAR_testing_dataset: ${{ inputs.testingDataset }}
        TF_VAR_demo_dataset: ${{ inputs.demoDataset }}