// Code generated by mockery v2.53.3. DO NOT EDIT.

package snowflake

import mock "github.com/stretchr/testify/mock"

// MockRoleNameGeneratorRepository is an autogenerated mock type for the RoleNameGeneratorRepository type
type MockRoleNameGeneratorRepository struct {
	mock.Mock
}

type MockRoleNameGeneratorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleNameGeneratorRepository) EXPECT() *MockRoleNameGeneratorRepository_Expecter {
	return &MockRoleNameGeneratorRepository_Expecter{mock: &_m.Mock}
}

// GetAccountRoles provides a mock function with no fields
func (_m *MockRoleNameGeneratorRepository) GetAccountRoles() ([]RoleEntity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccountRoles")
	}

	var r0 []RoleEntity
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]RoleEntity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []RoleEntity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RoleEntity)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleNameGeneratorRepository_GetAccountRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountRoles'
type MockRoleNameGeneratorRepository_GetAccountRoles_Call struct {
	*mock.Call
}

// GetAccountRoles is a helper method to define mock.On call
func (_e *MockRoleNameGeneratorRepository_Expecter) GetAccountRoles() *MockRoleNameGeneratorRepository_GetAccountRoles_Call {
	return &MockRoleNameGeneratorRepository_GetAccountRoles_Call{Call: _e.mock.On("GetAccountRoles")}
}

func (_c *MockRoleNameGeneratorRepository_GetAccountRoles_Call) Run(run func()) *MockRoleNameGeneratorRepository_GetAccountRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoleNameGeneratorRepository_GetAccountRoles_Call) Return(_a0 []RoleEntity, _a1 error) *MockRoleNameGeneratorRepository_GetAccountRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleNameGeneratorRepository_GetAccountRoles_Call) RunAndReturn(run func() ([]RoleEntity, error)) *MockRoleNameGeneratorRepository_GetAccountRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplicationRoles provides a mock function with given fields: application
func (_m *MockRoleNameGeneratorRepository) GetApplicationRoles(application string) ([]ApplicationRoleEntity, error) {
	ret := _m.Called(application)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationRoles")
	}

	var r0 []ApplicationRoleEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]ApplicationRoleEntity, error)); ok {
		return rf(application)
	}
	if rf, ok := ret.Get(0).(func(string) []ApplicationRoleEntity); ok {
		r0 = rf(application)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ApplicationRoleEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(application)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleNameGeneratorRepository_GetApplicationRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplicationRoles'
type MockRoleNameGeneratorRepository_GetApplicationRoles_Call struct {
	*mock.Call
}

// GetApplicationRoles is a helper method to define mock.On call
//   - application string
func (_e *MockRoleNameGeneratorRepository_Expecter) GetApplicationRoles(application interface{}) *MockRoleNameGeneratorRepository_GetApplicationRoles_Call {
	return &MockRoleNameGeneratorRepository_GetApplicationRoles_Call{Call: _e.mock.On("GetApplicationRoles", application)}
}

func (_c *MockRoleNameGeneratorRepository_GetApplicationRoles_Call) Run(run func(application string)) *MockRoleNameGeneratorRepository_GetApplicationRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRoleNameGeneratorRepository_GetApplicationRoles_Call) Return(_a0 []ApplicationRoleEntity, _a1 error) *MockRoleNameGeneratorRepository_GetApplicationRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleNameGeneratorRepository_GetApplicationRoles_Call) RunAndReturn(run func(string) ([]ApplicationRoleEntity, error)) *MockRoleNameGeneratorRepository_GetApplicationRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseRoles provides a mock function with given fields: database
func (_m *MockRoleNameGeneratorRepository) GetDatabaseRoles(database string) ([]RoleEntity, error) {
	ret := _m.Called(database)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseRoles")
	}

	var r0 []RoleEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]RoleEntity, error)); ok {
		return rf(database)
	}
	if rf, ok := ret.Get(0).(func(string) []RoleEntity); ok {
		r0 = rf(database)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RoleEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(database)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleNameGeneratorRepository_GetDatabaseRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseRoles'
type MockRoleNameGeneratorRepository_GetDatabaseRoles_Call struct {
	*mock.Call
}

// GetDatabaseRoles is a helper method to define mock.On call
//   - database string
func (_e *MockRoleNameGeneratorRepository_Expecter) GetDatabaseRoles(database interface{}) *MockRoleNameGeneratorRepository_GetDatabaseRoles_Call {
	return &MockRoleNameGeneratorRepository_GetDatabaseRoles_Call{Call: _e.mock.On("GetDatabaseRoles", database)}
}

func (_c *MockRoleNameGeneratorRepository_GetDatabaseRoles_Call) Run(run func(database string)) *MockRoleNameGeneratorRepository_GetDatabaseRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRoleNameGeneratorRepository_GetDatabaseRoles_Call) Return(_a0 []RoleEntity, _a1 error) *MockRoleNameGeneratorRepository_GetDatabaseRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleNameGeneratorRepository_GetDatabaseRoles_Call) RunAndReturn(run func(string) ([]RoleEntity, error)) *MockRoleNameGeneratorRepository_GetDatabaseRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleNameGeneratorRepository creates a new instance of MockRoleNameGeneratorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleNameGeneratorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleNameGeneratorRepository {
	mock := &MockRoleNameGeneratorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
