name: Raito CLI - Snowflake Plugin - Build
on:
  push:
    branches:
      - "main"
  pull_request:
permissions:
  id-token: write
  contents: read
jobs:
  remove-old-infra:
    uses: ./.github/workflows/destroy-roles.yml
    with:
      targetEnvironment: integration_testing
    secrets: inherit

  setup-infra:
    uses: ./.github/workflows/generate-infra.yml
    with:
      targetEnvironment: integration_testing
      demo-infra: false
      testing-infra: true
    secrets: inherit

    needs:
      - remove-old-infra
    if: always()

  generate-usage:
    uses: ./.github/workflows/generate-usage.yml
    with:
      targetEnvironment: integration_testing
    secrets: inherit

    needs:
      - setup-infra

  build:
    environment: integration_testing
    runs-on: ubuntu-latest

    needs:
      - setup-infra
      - generate-usage

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_DEPLOY_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Mod Tidy
        run: go mod tidy

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.56.1

      - name: Test
        run: make test
        env:
          SF_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SF_USER: ${{ secrets.SNOWFLAKE_USER }}
          SF_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SF_ROLE: ${{ secrets.sf_role }}
          SF_STANDARD_EDITION: false

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt

#  cleanup:
#    needs:
#      - setup-infra
#      - build
#    if: always() && needs.setup-infra.result == 'success'
#
#    uses: ./.github/workflows/destroy-infra.yml
#    with:
#      targetEnvironment: integration_testing
#    secrets: inherit

