name: Manual - Destroy roles
on:
  workflow_call:
    inputs:
      targetEnvironment:
        required: true
        type: string
    secrets:
      SNOWFLAKE_ACCOUNT:
        required: true
      SNOWFLAKE_USER:
        required: true
      SNOWFLAKE_PASSWORD:
        required: true
      SNOWFLAKE_ORGANIZATION:
        required: true
  workflow_dispatch:
    inputs:
      targetEnvironment:
        type: choice
        description: Please select a target environment
        required: true
        default: 'integration_testing'
        options:
          - integration_testing
          - testing
permissions:
  id-token: write
  contents: read
jobs:
  destroy-infra:
    environment: ${{ inputs.targetEnvironment }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/destroy-roles
        with:
          snowflakeAccount: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          snowflakeUser: ${{ secrets.SNOWFLAKE_USER }}
          snowflakePassword: ${{ secrets.SNOWFLAKE_PASSWORD }}
          snowflakeOrganization: ${{ secrets.SNOWFLAKE_ORGANIZATION }}