name: Manual - Destroy roles
on:
  workflow_call:
    inputs:
      targetEnvironment:
        required: true
        type: string
    secrets:
      SNOWFLAKE_ACCOUNT:
        required: true
      SNOWFLAKE_USER:
        required: true
      SNOWFLAKE_PRIVATE_KEY:
        required: true
      SNOWFLAKE_ORGANIZATION:
        required: true
  workflow_dispatch:
    inputs:
      targetEnvironment:
        type: choice
        description: Please select a target environment
        required: true
        default: 'integration_testing'
        options:
          - integration_testing
          - testing
permissions:
  id-token: write
  contents: read
jobs:
  destroy-infra:
    environment: ${{ inputs.targetEnvironment }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Mod Tidy
        shell: bash
        run: go mod tidy

      - name: Store private key to file
        shell: bash
        run: echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > /tmp/snowflake_private_key.pem

      - uses: ./.github/actions/destroy-roles
        with:
          snowflakeAccount: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          snowflakeUser: ${{ secrets.SNOWFLAKE_USER }}
          snowflakePrivateKey: /tmp/snowflake_private_key.pem
          snowflakeOrganization: ${{ secrets.SNOWFLAKE_ORGANIZATION }}