name: Raito CLI - Snowflake Plugin - Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Granting private modules access
        run: git config --global url."https://${{ secrets.CI_SECRETS_TOKEN }}:x-oauth-basic@github.com/raito-io".insteadOf "https://github.com/raito-io"
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.CI_SECRETS_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{github.ref_name}}